feedhenry/fh-js-sdk

src/modules/appProps.js

Rebased with FHMOBSDK-57-support-mbaas-auth.
Closes #112

FHMOBSDK 53 local fh params (Rebase FHMOBSDK 57)

---

package.json
src/appforms/src/core/020-utils01fileSystem.js

@nialldonnellyfh as discussed on IRC

workaround for windows file plug-in missing fullPath property on File

---

package.json
src/appforms/src/backbone/040-view02field29barcode.js
src/appforms/src/backbone/040-view04Form.js
src/appforms/src/backbone/041-view01ConfigView.js
src/appforms/src/backbone/050-api.js

Windows 8.1 does not allow using the alert function available to browsers.

Replaced alert with cordova alert if available

---

src/modules/api_push.js
test/tests/test_push.js

Fixes issue [RHMAP-2080](https://issues.jboss.org/browse/RHMAP-2080)

now one can update categories and alias outside of the config

---

src/modules/api_push.js

removes the need for pushServerURL to be in fhconfig.json

RHMAP-3268 construct push url from host

---

src/modules/api_act.js
src/modules/api_auth.js
src/modules/api_mbaas.js
src/modules/initializer.js

Fixes [RHMAP-5835](https://issues.jboss.org/browse/RHMAP-5835)
@wei-lee could you review

use jsonp as fallback for Titanium as well

---

CHANGELOG.md
package.json
src/appforms/src/backbone/040-view04Form.js

fixing issue [RHMAP-6428](https://issues.jboss.org/browse/RHMAP-6428)
@nialldonnellyfh don't know if this solution is sound, but it works ;)

removed call that removes images

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/appforms/script/sampleData/getForm.json
src/appforms/script/sampleData/getForms.json
src/appforms/src/backbone/040-view02field27dateTime.js
src/appforms/src/core/060-RuleEngine.js
src/appforms/tests/tests/backbone/040-view02field27dateTime.js

This allows a dateTime field with a custom format to be displayed on the field and also validated with an update to the rules engine.

Added dateTime placholder for custom dateTime field formats

---

CHANGELOG.md
src/modules/data.js

@wei-lee need to add this on android as it doesn't have a window name

added memory fallback for titanium android

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/appforms/src/core/040-Model06Submission.js

Bug Report - Drag & Drop Forms
If the forms app has pending submissions and the form relating to that submission is changed where a field is removed and deployed the user can no longer submit this submission.

Rhmap 7618 form submissions stuck in review when field is deleted from server side

---

src/modules/titanium/ti.js

added wrapper around AeroGear-Push-Titanium module

---

CHANGELOG.md
bower.json
npm-shrinkwrap.json
package.json
src/appforms/src/core/000-api-v2.js

@nialldonnellyfh like discussed on slack

use window object for browser use

---

.npmignore
CHANGELOG.md
README.md
npm-shrinkwrap.json
package.json

New.npm.release

---

src/modules/ajax.js
src/modules/api_act.js
src/modules/api_cloud.js

This fixes #149 by removing the `__fh` property from req.query and req.body. These values are already in headers so this should be fine 👍

remove __fh from body/query (issue #149)

---

src/appforms/src/core/040-Model06Submission.js
src/appforms/tests/tests/core/040-Model06Submission.js

Added tests for the form state functionality.

Added tests for adding form values

---

.gitignore
fh-js-sdk.d.ts
package.json

TypeScript should now be able to find the definition file when
importing the SDK automatically.
* Add signatures to all public-by-default methods in the SDK
* Add JSDoc comments to the method signatures
* Bump version of SDK

RHMAP-7811 Add declaration file for TypeScript

---

npm-shrinkwrap.json
package.json
src/appforms/src/core/060-RuleEngine.js

Updated the rules engine related to https://github.com/feedhenry/fh-forms/pull/3

Rhmap 11544 add blank required

---

src/modules/appProps.js

@nialldonnellyfh Mind a review?
this is a PR to enable local dev environment.

fhconfig.json with local:true and host will skip FH.init for local dev

---

npm-shrinkwrap.json
package.json

Release 2.18.3

---

npm-shrinkwrap.json
package.json
src/appforms/src/backbone/040-view02field14field_map.js
src/appforms/tests/tests/backbone/040-view02field14field_map.js

Added handling to the map backbone field to handle the case where a location was not found.
It will use a default set of coordinates.

Rhmap 13542 fix map display after geolocation error

---

CHANGELOG.md
package.json
src/appforms/src/core/060-RuleEngine.js

Related to https://github.com/feedhenry/fh-forms/pull/11

Upgraded the rules engine

---

fh-js-sdk.d.ts

The _hasSession_ and _verifySession_ FH.Auth functions were not defined.
I also noticed that my editor removed some whitespace. I can fix that if needs be.

add missing functions to typescript definitions

---

npm-shrinkwrap.json
package.json
src/appforms/.jshintrc
src/appforms/src/core/040-Model07Field.js
src/appforms/tests/modules.js
src/appforms/tests/tests/core/040-Model07FieldSections.js

https://issues.jboss.org/browse/RHMAP-4793
add get sectionId for the field model that should return fieldId of the parent section
Added new function to `Field` model
@jhellar

RHMAP-4793 added getSectionId for the field model

---

src/appforms/src/backbone/040-view02field01field.js
src/appforms/src/backbone/040-view02section.js
src/appforms/src/backbone/040-view03Page.js
src/appforms/src/backbone/040-view04Form.js
src/appforms/tests/tests/backbone/040-view02field01field.js

https://issues.jboss.org/browse/RHMAP-9286

Fix validation errors for repeating sections

---

src/appforms/src/core/040-Model06Submission.js

https://issues.jboss.org/browse/RHMAP-17078
- create form with 2 pages
- create text field for first page
- create repeating section for second page with max repeat set to 10000
- create a text field for this repeating section
- create a page rule where source is the first text field and target is the second page, which should be hidden when condition is met
- open the form in client app
- set the first field so that the second page is hidden
- submit the form
- check submission with developer tools

Fix for remove hidden fields

---

src/appforms/tests/modules.js
src/appforms/tests/tests/core/070-RepeatingSections.js

https://issues.jboss.org/browse/RHMAP-10204

Tests for appforms repeating sections

---

src/appforms/tests/modules.js
src/appforms/tests/tests/backbone/050-repeatingSections.js

https://issues.jboss.org/browse/RHMAP-17179

Added test for repeating sections - draft, sent

---

src/appforms/tests/tests/backbone/050-repeatingSections.js

https://issues.jboss.org/browse/RHMAP-17180
https://issues.jboss.org/browse/RHMAP-17182
https://issues.jboss.org/browse/RHMAP-17183

Added tests for repeating sections

---

src/appforms/tests/tests/core/040-Model06Submission.js

https://issues.jboss.org/browse/RHMAP-17184

Added test for repeating sections - getSectionValues

---

src/appforms/src/core/040-Model06Submission.js

https://issues.jboss.org/browse/RHMAP-17379

Fix for file uploads with repeating sections

---

src/appforms/src/core/040-Model06Submission.js

https://issues.jboss.org/browse/RHMAP-17405

Fix download of submissions with files in repeating sections

---

src/appforms/src/backbone/040-view04Form.js

fix the bug related to hiding fields outside sections.
https://issues.jboss.org/browse/RHMAP-17394
@jhellar

hide fields not in sections

---

src/appforms/src/core/040-Model06Submission.js

In https://github.com/feedhenry/fh-js-sdk/pull/237 there was an issue, which caused `$fh.forms.downloadSubmission with files` test case to fail.

Fix for getFieldValues

---

package.json
src/appforms/src/core/060-RuleEngine.js

https://issues.jboss.org/browse/RHMAP-6621

Making Repeating Fields Non-Mandatory

---

npm-shrinkwrap.json
package.json

@wtrocki 
version bump as previous merge didnt have it

version bump

---

npm-shrinkwrap.json
package.json
src/appforms/src/core/060-RuleEngine.js

Related to the updated [fh-forms](https://github.com/feedhenry/fh-forms/pull/31) changes

Rhmap 16295 studio xss fixes

---

npm-shrinkwrap.json
package.json
src/appforms/script/sampleData/getForm.json
src/appforms/src/backbone/040-view02field05field_checkbox.js
src/appforms/tests/tests/backbone/040-view02field05field_checkbox.js
src/appforms/tests/vendor/async.js

JIRA https://issues.jboss.org/browse/RHMAP-19045
previous JQuery selector was invalid.
@davidffrench 
@twnolan pinging you as you are fairly familiar with JQuerry selectors and might hint to better option
Im searching by  choice_icon and getting value of the parent to get the option value
```
<div id="wrapper_5a3112ecaad82910f80a1f62_0" class="col-xs-12 fh_appform_field_wrapper">
<div class="fh_appform_field_input_container repeating col-xs-12">
<div class="btn-group-vertical fh_appform_field_input col-xs-12 non_repeating" data-
toggle="buttons-checkbox">
<button class="btn btn-primary text-left fh_appform_button_action col-xs-12" 
type="button" value="Option 1" name="5a3112ecaad82910f80a1f62[]"
data-field="5a3112ecaad82910f80a1f62" data-index="0">
<i class="icon-check-empty …
```

fixed get value from element

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

@camilamacedo86 The changelog entry doesn't reference a JIRA. A few previous logs don't either. Happy to create one though if needed.

Bump version to 3.0.1

---

CHANGELOG.md
licenses/HAS_MIT.TXT
licenses/licenses.html
licenses/licenses.xml
npm-shrinkwrap.json
package.json

https://issues.jboss.org/browse/RHMAP-20434
- Add scripts to update the licenses automatically
- Update licenses and npm-shrinkwrap.json 
It is a RedHat pre-requirement. 
Check if the CI process finalized with success.

RHMAP-20434 : Add scripts to update the licenses automatically

---

CHANGELOG.md
package-lock.json
package.json

https://issues.jboss.org/browse/RHMAP-20023
Update version of fh-sync-js to 1.3.2
Version bump to 3.0.10
Changelog update
To pull in this fix: https://github.com/feedhenry/fh-sync-js/pull/45

Upgrade version of fh-sync-js
