CHANGELOG.md
bower.json
npm-shrinkwrap.json
package.json
src/appforms/src/core/020-utils.js
src/appforms/src/core/040-Model.js
src/appforms/src/core/040-Model06Submission.js
src/appforms/src/core/040-Model12UploadTask.js
src/appforms/src/core/050-api.js
src/appforms/tests/tests/core/040-Model06Submission.js
src/appforms/tests/tests/core/050-api.js

Added A global event listener for appforms model events.
With this change, a user can call: e.g.
$fh.forms.on("modelType:eventname", function(){})
and
$fh.forms.once("modelType:eventname", function(){})  
to register for all events from different submissions.

Added A Global Event Listener For Appforms APIs

---

CHANGELOG.md
bower.json
npm-shrinkwrap.json
package.json
src/appforms/src/core/050-api.js
src/appforms/tests/tests/core/050-api.js

This allows users to call the $fh.forms.downloadSubmission API without the callback.
This will queue the submission for download and global events can then be used to subscribe to the submission download events.

Added event driven approach to fh.forms.downloadSubmission API

---

CHANGELOG.md
bower.json
package.json
src/appforms/src/core/040-Model07FieldFile.js

This fix resolves an issue in the $fh.forms API where file extensions were not being kept when cacheing files.

Fixed Cached File Extension Bug

---

CHANGELOG.md
package.json
src/appforms/src/core/000-api-v2.js

This fixes issue [RHMAP-2970](https://issues.jboss.org/browse/RHMAP-2970) as appforms is overriding the push api

remove override of push function

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/modules/appProps.js

decode config overrides when they are loaded via query string

decode the parameters in the url query string

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/appforms/script/sampleData/getForm.json
src/appforms/src/backbone/040-view02field01field.js
src/appforms/src/backbone/040-view02field10field_file.js
src/appforms/src/backbone/040-view02field21field_signature.js
src/appforms/src/backbone/040-view02field29barcode.js
src/appforms/src/backbone/040-view02field30sliderNumber.js
src/appforms/src/backbone/040-view04Form.js
src/appforms/tests/tests/backbone/040-view02field01field.js

Currently, when the field values changes, the rules state is not being updated immediately as the updated field values have not been applied to the submission yet.
This change ensures that the updated field values are always added to the submission before checking for the rule state.
- Updated the FieldModel to add input values to the submission when the `contentChange` event is fired by a field.

Ensuring that field and page rules are applied immediately.

---

src/appforms/src/core/040-Model06Submission.js

Part of file field binding spike [RAINCATCH-122](https://issues.jboss.org/browse/RAINCATCH-122)
added `addFileValue` function that can be called for file type fields and updates its value in sdk
@nialldonnellyfh @paolobueno @TommyJ1994

Raincatch 122 file field binding

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/appforms/src/core/040-Model06Submission.js
src/appforms/src/core/040-Model07Field.js
src/appforms/tests/tests/core/040-Model06Submission.js

When a new submission is created with a form, it should automatically apply the default values for the field.
This is to ensure that any default values that affect rules are applied before testing rule values.
- Added a `applyDefaultValues` function to the submission model. This is called when a new submission is initialised with a form.
- Added logic to the Field model to get default values from multi-choice and non-multichoice fields.

Rhmap 10243 apply default values

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

Adding a post install script to generate the dist folder when the fh-js-sdk has been installed.

Bump to 2.7.3

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/modules/sync-cli.js

This allows users to check for sync records where `uid`s may have changed.
The changed `uid`s are emitted in notifications and any function filtering on the old `uid` will not filter correctly.

Allowing users to get UIDs for sync records.

---

npm-shrinkwrap.json
package.json
src/appforms/src/core/040-Model06Submission.js
src/appforms/tests/tests/core/040-Model06Submission.js

When a form is being submitted, any hidden fields with values also get submitted.
These values in hidden fields should be removed.
- Added a `removeHiddenFieldValues` function to remove any hidden field values.

Rhmap 11349 dont submit hidden values

---

npm-shrinkwrap.json
package.json
src/appforms/src/core/040-Model08Page.js
src/appforms/tests/tests/core/040-Model08Page.js

The section break IDs returned from a page were not guaranteed to be unique across multiple pages.
This change ensures that the section IDs returned from a page are unique.
Updated the `getSections` function for the `Page` model to assign the field ID of the section field as the ID. All field IDs are guaranteed to be unique.

Rhmap 12426 fix section dropdown

---

libs/lawnchair/lawnchairHtml5FileSystem.js

FileError is obsolete and was removed in most recent versions of the mobile browsers:
https://developer.mozilla.org/en-US/docs/Web/API/FileError
This fix removes error I have seen when testing sample app. I did not seen any other errors and rest of the html5 filesystem api seems to be working fine. However Lawnchair library is fairly outdated and it would be better to update it for better future browser support.
ping @david-martin @wei-lee 
More information in ticket: https://issues.jboss.org/browse/RAINCATCH-570

RAINCATCH-570 - update to the new browser api

---

src/modules/device.js

Currently when the value of a cookie is blank it is read as an empty
string. This passes the current check that is looking for the value
being `null`. If the value is `null` the cookie will be recreated.
This behaviour will cause fh-mbaas-api to throw an error, as it checks
whether the CUID sent from the client is a falsy value. If it is, it will produce
an error and fail to process the pending record.
This changes the check on the client SDK to match that of fh-mbaas-api
so that empty-string device ids will be recreated as well as `null` ones.

Recreate mock_uuid cookie if blank string

---

fh-js-sdk.d.ts

When using FH.Sync like so the code compiles fine:
```ts
import { Sync } from 'fh-js-sdk'
Sync.doUpdate('todos', todoId, todoData, successCb, failureCb);
```
At runtime this will fail since the generated code is:
```js
fh.Sync.doUpdate
```
but we really need
```js
fh.sync.doUpdate
```

fix sync namespace to user lowercase name

---

npm-shrinkwrap.json
package.json

Referenced in #210 -  We need this to be able to bundle `fh-js-sdk` in other projects using browserify.

add browserify-shim as a dependency

---

src/appforms/src/backbone/040-view02field01field.js
src/appforms/src/backbone/040-view02section.js
src/appforms/src/backbone/040-view04Form.js
src/appforms/src/core/040-Model06Submission.js

https://issues.jboss.org/browse/RHMAP-17078
- all repeating sections are not generated initially, rather they are being generated as needed
- small fixes - pass `sectionIndex` as parameter
1. have a form with repeating section
2. try to submit form with only one section
3. submission should contain only values from the first section

Prune empty values in repeating sections

---

src/appforms/src/backbone/040-view02section.js
src/appforms/src/backbone/040-view04Form.js
src/appforms/src/core/040-Model06Submission.js
src/appforms/src/core/060-RuleEngine.js

https://issues.jboss.org/browse/RHMAP-17087
- source field is outside of repeating section and target is in a repeating section
- both source and target fields are in a same repeating section
- submissions values should be removed from hidden fields

Fix field rules for repeating sections

---

src/appforms/src/core/040-Model06Submission.js

https://issues.jboss.org/browse/RHMAP-9426
- in `040-Model06Submission.js` after line 247 add this code:
```
var repSec;
for (var key in formModel.fields) {
var field = formModel.fields[key];
if (field.props.type === 'sectionBreak' && field.props.repeating) {
repSec = field;
}
}
self.getSectionValues(repSec.props._id, 0, function(err, v) {
console.log('TEST', v);
});
```
- submit form and check console, there should be list of values for first repeating section

Add a getSectionValues API to the Submission model

---

npm-shrinkwrap.json
package.json

Update version of the sync client. 
It looks like version weren't updated for a while.
Related sync change: 
https://github.com/feedhenry/fh-sync-js/pull/31
I'm going to run set of standard tests on this version to make sure that we do not have any regression issues. 
1) Use sync acceptance testing project:
https://github.com/feedhenry/sync-acceptance-testing
2) npm link this version fh-js-sdk 
3) Run tests
1) Run sync on the cloud (nothing required)
2) Use tutorial application to test cloud app.
https://github.com/feedhenry-templates/sync-tutorial-app/

Version bump fh-sync-js

---

npm-shrinkwrap.json
package.json
src/appforms/src/core/060-RuleEngine.js

The form input is validated in the app preview and due to the changes in this ticket [RHMAP-9354](https://issues.jboss.org/browse/RHMAP-9354) (where special characters in a form label get escaped) the form label does not match the form field value and therefore throws a validation error because they don't match.
Escape the form field value too
https://issues.jboss.org/browse/RHMAP-16297

Rhmap 16295 studio xss fixes

---

src/appforms/src/core/040-Model06Submission.js

When iterating a large number of fields in a form to remove hidden fields it results in an overflow of the call stack due to a synchronous if block where we don't clean up localstorage. 
https://github.com/feedhenry/fh-js-sdk/blob/146b72715cb1625eb9f472ca3f9f7cf9b5016f3d/src/appforms/src/core/040-Model06Submission.js#L983
This is happening due to a removed guard in async versions 2+. More details and reading here: https://github.com/caolan/async/blob/master/intro.md#synchronous-iteration-functions
Defer callback inside a synchronous block using async.setImmediate. (See https://github.com/caolan/async/blob/master/intro.md#synchronous-iteration-functions) 
https://issues.jboss.org/browse/RHMAP-18146

RHMAP-18146 - Stop overflowing call stack when doing large synchronous iterations 

---

npm-shrinkwrap.json
package.json
src/appforms/src/core/060-RuleEngine.js

- Needed to check if the form field values and form labels in radio and dropdown form fields had already been escaped. There were being escaped twice during the validation which was causing a mismatch in the two values when being compared and thus validation errors
- https://issues.jboss.org/browse/RHMAP-18065

RHMAP-16295: XSS update - check if string has already been escaped

---

CHANGELOG.md
bower.json
npm-shrinkwrap.json
package.json
src/modules/initializer.js

Ref the Issue: https://github.com/feedhenry/fh-js-sdk/issues/256
JIRA: https://issues.jboss.org/browse/RHMAP-19268  
**Root cause:** The validation/implementation `req.status` was added without considering that the `req` can be `undefined` in some situation. In order to prove it note that the `req` is checked at another point implemented previously. ( https://github.com/feedhenry/fh-js-sdk/blob/2.23.0/src/modules/initializer.js#L81 )

FIX: RHMAP-19268 - Client gets null pointer exception when connection tag is disabled

---

.travis.yml

https://issues.jboss.org/browse/RHMAP-20276
Update NodeJS version to use 4, 6, and 8 as follows.
```
node_js:
- '4'
- '6'
- '8'
```
The current version adopted for RHMAP is 6.11.3 and the version 0.10 used here is deprecated.  
Check if the all steps in Trevis are finishing with success.

[task] - FH-4890: Update NodeJS version on travis to 6.11.3

---

CHANGELOG.md
fh-js-sdk.d.ts
package.json

Correct the type definition for the `sync.setQueryParams` function.
The current definition for `sync.setQueryParams` is incorrect and causes errors when using this function within a TypeScript application.
Changing the `fh-js-sdk.d.ts` file to match the `setQueryParams` function found [here](https://github.com/feedhenry/fh-sync-js/blob/master/src/sync-client.js#L407).
- Open the source code for the `setQueryParams` function [here](https://github.com/feedhenry/fh-sync-js/blob/master/src/sync-client.js#L407).
- Verify the new definition matches the function signature in the `fh-sync-js` repo.

Add queryParams to setQueryParams definition

---

CHANGELOG.md
npm-shrinkwrap.json
package.json

https://issues.jboss.org/browse/RHMAP-20720
- Remove moment dependency from dev dependencies because it is not used.
* Solve vulnerability. For further information check: https://nvd.nist.gov/vuln/detail/CVE-2017-18214
* Dep not used
No usage, it was declared in the dev deps. 
* Run `grunt` tasks and/or check if the CI/Travis in PR was succeeded

task(CVE-2017-18214): RHMAP-20720 - Remove moment dependency

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/modules/fhparams.js

https://issues.jboss.org/browse/RHMAP-19117
Some FH request headers are not formatted correctly. Following an example. 
```javascript
X-FH-init:[object Object]
```
Because the code which creates ALL params of the header is not expecting an object. 
```javascript
headers['X-FH-' + name] = params[name];
```
By transforming objects in JSON 
```javascript
headers['X-FH-' + name] = JSON.stringify(params[name]);
```
* Clone this PR
* Run `npm install` and `grunt`
* Create a Cordova Hello World project and update the main.js file of the client application with this content. 
* Follow the steps described in the JIRA to reproduce the issue. 
* The header values should not so long be as [Object Object] 
Following local test.

fix(Some FH request headers are not formatted correctly): RHMAP-19117

---

CHANGELOG.md
npm-shrinkwrap.json
package.json
src/appforms/src/backbone/040-view02field27dateTime.js

https://issues.jboss.org/browse/RHMAP-19715
The rules set up for the form is not applied when the value is added by the button.  
When the date is set by the button the validate rules are not called and the rules configured for this form is not applied. 
When the value is added manually:
When the value is added via the button it is like empty:
Change the event used when the button is called. 
- Go to the studio
- Create a new form project
- Create a new form as follows. 
** With: date component, and an input A, and an input B
** Create a rule to show the input A just if the date is upper than `2017-01-01 00:00:00`
- Deploy the form
- Associated the form the form project created
- Deploy the cloud app for this project
- Update the `www/lib.min.js` with the content of this SDK
- Open the …

RHMAP-19715 - Fix date form component which is not working when the button is used 

---

CHANGELOG.md

https://issues.jboss.org/browse/RHMAP-21715
Update changelog in order to avoid users use deprecated versions of SDK
In the 3.0.3 was introduced an issue which is fixed in the version 3.0.11, besides this intermediate versions be not released with the product this change is required in order to make clear that these versions are deprecated and should not be used since has this bug.

Update changelog in order to avoid users use deprecated versions of SDK

---

CHANGELOG.md
package-lock.json
package.json
src/modules/initializer.js

https://issues.jboss.org/browse/RHMAP-22002
Add default result for init requests across domains when the result is not successful which is expected when the connection tag is disable.
In this situation all values are returned as undefined which has been a complain by its users.
If all be undefined then return a descriptive and default message. 
1. Create a WebApp project
2. Clone locally this PR and run ( npm install and grunt )
3. Update the main.js file in the client web app in the platform with the "dist/feedhenry.js" generated locally.
4. Disable the connection tab 
5. Copy the index.html and hello.js to the public dir of the web client app
6. Update the index.html to looking for hello.js in the public dir
7. Deploy it
8. Test it by the preview. The following result is the expected …

Add message when has error to initializer
